export const T = {
  // === Spec Asana ===
  PRIMARY:      '#1B3A6B',
  ACCENT:       '#F59E0B',
  CARD_RADIUS:  '20px',
  FONT_PRIMARY: "'Nunito', sans-serif",

  // === Marca GUARDIUM (rojo/negro) ===
  RED:        '#C0202A',
  RED_DARK:   '#8B1219',
  RED_LIGHT:  '#D94550',
  RED_MUTED:  '#F5E0E1',
  BLACK:      '#1A1A1A',
  BLACK_SOFT: '#2C2C2C',
  CHARCOAL:   '#3D3D3D',
  STEEL:      '#6B6B6B',
  SILVER:     '#A8A8A8',
  BORDER:     '#E5E5E5',
  BG:         '#F5F5F5',
  BG_DARK:    '#EFEFEF',
  WHITE:      '#FFFFFF',
  TEXT:       '#1A1A1A',
  TEXT_MUTED: '#6B6B6B',
  TEXT_LIGHT: '#A8A8A8',
  SUCCESS:    '#22C55E',
  SUCCESS_BG: '#DCFCE7',
  WARN:       '#F59E0B',
  WARN_BG:    '#FEF3C7',
  DANGER:     '#EF4444',
  DANGER_BG:  '#FEE2E2',
  INFO:       '#3B82F6',
  INFO_BG:    '#DBEAFE',
  ORANGE:     '#F97316',
  ORANGE_BG:  '#FFF7ED',
  MUTED:      '#94A3B8',
  MUTED_BG:   '#F1F5F9',
  RADIUS:     '18px',
  RADIUS_SM:  '10px',
  SHADOW:     '0 2px 16px rgba(0,0,0,0.07)',
  SHADOW_LG:  '0 6px 32px rgba(0,0,0,0.13)',
  FONT_DISPLAY: "'Bebas Neue', cursive",
  FONT_BODY:    "'Nunito', sans-serif",
}
